language: node_js
node_js:
- '0.12'
before_install:
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
- npm install -g gulp
- npm install -g jspm
- jspm config registries.github.auth $GH_TOKEN
before_script:
- jspm install
script:
- gulp test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b8370848156125f09831
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
#addons:
#  sauce_connect: true
